import type { TestProcedure } from '../types'

/**
 * PROCEDIMENTO DE DESENERGIZAÇÃO (NR-10 item 10.5.1) + REENERGIZAÇÃO (10.6,
 * ordem inversa). Cada passo tem ação 3D, detalhes, cuidados, erros comuns e
 * mensagem de resultado. Navegação MANUAL (Próximo/Voltar). Modo 'desenergizacao'.
 */
export const desenergizacaoProcedure: TestProcedure = {
  id: 'desenergizacao-subestacao',
  nome: 'Procedimento de Desenergização',
  norma: 'NR-10 · 10.5 / 10.6',
  instrumento: 'checklist',
  engineRef: 'desenergizacao',
  modo: 'desenergizacao',
  tensoes: [],
  tensaoPadrao: 0,
  duracaoS: 0,
  steps: [
    {
      id: 'des-apr',
      titulo: 'Planejamento e EPI',
      descricao: 'Antes de tudo: análise de risco, permissão de trabalho e equipamentos de proteção.',
      detalhes: [
        'APR / Permissão de Trabalho (PT) emitida',
        'EPI: vestimenta FR, luvas isolantes + cobertura de vaqueta, capacete c/ viseira',
        'EPC: detector de tensão, conjunto de aterramento, cadeados/etiquetas (LOTO)',
        'Delimitação e controle de acesso à área',
      ],
      cuidados: [
        'Confirme a tensão e o esquema (unifilar) do circuito antes de iniciar.',
        'Inspecione os EPI: luvas isolantes testadas e sem furos.',
        'Defina o responsável pela chave de bloqueio.',
      ],
      erros: [
        'Iniciar sem PT/APR assinada.',
        'Usar luva isolante vencida ou sem cobertura de vaqueta.',
        'Não delimitar a zona de trabalho.',
      ],
      feito: 'Planejamento confirmado. EPI/EPC prontos para iniciar.',
      acao: 'Confirmar planejamento',
      acaoTipo: 'confirmar',
      norma: 'NR-10',
    },
    {
      id: 'des-seccionar',
      titulo: '1. Seccionamento',
      descricao: 'Abra o circuito no disjuntor e na seccionadora, criando abertura comprovável.',
      detalhes: ['Abrir disjuntor', 'Abrir seccionadora (abertura visível)', 'Confirmar indicação de aberto'],
      cuidados: [
        'Opere na sequência correta: primeiro o disjuntor (sob carga), depois a seccionadora.',
        'Confirme a abertura pela sinalização (vermelho→verde) e, se possível, visualmente.',
      ],
      erros: [
        'Abrir a seccionadora sob carga (risco de arco).',
        'Confiar só na botoeira sem confirmar a posição real.',
      ],
      feito: 'Disjuntor e seccionadora abertos — circuito seccionado (luz verde).',
      acao: 'Seccionar circuito',
      acaoTipo: 'seccionar',
      requer: ['des-apr'],
      focoAnchorId: 'disjuntor',
    },
    {
      id: 'des-bloquear',
      titulo: '2. Impedimento de reenergização',
      descricao: 'Bloqueie o dispositivo (LOTO) e instale etiqueta de advertência.',
      detalhes: ['Cadeado/dispositivo LOTO na manopla', 'Etiqueta com nome/data/responsável', 'Chave sob controle do executante'],
      cuidados: [
        'Use dispositivo de bloqueio (LOTO) que impeça fisicamente a manobra.',
        'Cada trabalhador deve ter o seu cadeado (bloqueio múltiplo, se aplicável).',
        'A chave do cadeado fica com quem executa o serviço.',
      ],
      erros: [
        'Só etiquetar sem cadear.',
        'Deixar a chave do cadeado no quadro.',
        'Bloqueio que não impede a manobra.',
      ],
      feito: 'Dispositivo LOTO instalado e etiquetado — reenergização impedida.',
      acao: 'Aplicar bloqueio',
      acaoTipo: 'bloquear',
      requer: ['des-seccionar'],
      focoAnchorId: 'bloqueio',
    },
    {
      id: 'des-testar',
      titulo: '3. Constatação de ausência de tensão',
      descricao: 'Teste com detector de tensão (técnica vivo–morto–vivo) em todas as fases.',
      detalhes: ['Testar detector em fonte energizada', 'Testar o circuito (deve dar ausência)', 'Reconfirmar o detector na fonte'],
      cuidados: [
        'Detector adequado à tensão (MT) e dentro da validade de calibração.',
        'Teste vivo–morto–vivo: comprove que o detector funciona antes e depois.',
        'Verifique TODAS as fases.',
      ],
      erros: [
        'Não fazer o teste vivo–morto–vivo (detector pode estar com defeito).',
        'Testar só uma fase.',
        'Usar detector de BT em MT.',
      ],
      feito: 'Ausência de tensão confirmada nas três fases.',
      acao: 'Testar tensão',
      acaoTipo: 'testar',
      requer: ['des-bloquear'],
      focoAnchorId: 'teste',
    },
    {
      id: 'des-aterrar',
      titulo: '4. Aterramento temporário',
      descricao: 'Instale o conjunto de aterramento temporário com equipotencialização das fases.',
      detalhes: ['Conectar PRIMEIRO ao terra/malha', 'Depois aos condutores (todas as fases)', 'Equipotencializar a zona de trabalho'],
      cuidados: [
        'Ordem de conexão: terra primeiro, depois os condutores.',
        'Conjunto de aterramento com seção adequada à corrente de curto.',
        'Aterre nos dois lados do ponto de trabalho, se houver alimentação por ambos.',
      ],
      erros: [
        'Conectar nos condutores antes do terra.',
        'Cabo de aterramento subdimensionado.',
        'Esquecer uma das fases.',
      ],
      feito: 'Fases aterradas e equipotencializadas.',
      acao: 'Instalar aterramento',
      acaoTipo: 'aterrar',
      requer: ['des-testar'],
      focoAnchorId: 'aterramento',
    },
    {
      id: 'des-proteger',
      titulo: '5. Proteção de partes vivas',
      descricao: 'Isole/coloque barreiras nas partes energizadas próximas na zona controlada.',
      detalhes: ['Mantas/coberturas isolantes', 'Barreiras físicas', 'Demarcar partes que permanecem vivas'],
      cuidados: [
        'Identifique o que permanece energizado ao redor.',
        'Use coberturas isolantes adequadas à tensão.',
        'Mantenha as distâncias de segurança (zona controlada/de risco).',
      ],
      erros: [
        'Ignorar circuitos adjacentes ainda energizados.',
        'Barreira que não suporta a tensão.',
      ],
      feito: 'Partes vivas próximas protegidas e demarcadas.',
      acao: 'Proteger partes vivas',
      acaoTipo: 'proteger',
      requer: ['des-aterrar'],
      focoAnchorId: 'protecao',
    },
    {
      id: 'des-sinalizar',
      titulo: '6. Sinalização',
      descricao: 'Instale a sinalização de impedimento de reenergização.',
      detalhes: ['Placa "PROIBIDO OPERAR A CHAVE"', 'Sinalização no comando e no local', 'Identificar o circuito'],
      cuidados: [
        'Sinalize tanto no ponto de manobra quanto no local de trabalho.',
        'A sinalização deve ser visível e clara.',
      ],
      erros: ['Sinalizar só num ponto.', 'Placa sem identificação do responsável/circuito.'],
      feito: 'Sinalização instalada: "PROIBIDO OPERAR A CHAVE".',
      acao: 'Sinalizar',
      acaoTipo: 'sinalizar',
      requer: ['des-proteger'],
      focoAnchorId: 'sinalizacao',
    },
    {
      id: 'des-liberado',
      titulo: 'Liberado para o trabalho',
      descricao: 'Sequência completa: instalação desenergizada conforme NR-10. Trabalho autorizado.',
      detalhes: ['Todas as 6 etapas concluídas', 'Estado de segurança confirmado'],
      cuidados: ['Reconfira o estado de segurança antes de liberar a equipe.'],
      feito: 'Instalação desenergizada e segura — pode iniciar a manutenção.',
      acao: 'Confirmar liberação',
      acaoTipo: 'confirmar',
      requer: ['des-sinalizar'],
    },
    // ---------- REENERGIZAÇÃO (ordem inversa, NR-10 10.6) ----------
    {
      id: 'reen-conferir',
      titulo: 'Fim do trabalho — conferência',
      descricao: 'Confirme término do serviço, retirada de ferramentas e afastamento das pessoas.',
      detalhes: ['Pessoas fora da zona de risco', 'Ferramentas/materiais retirados', 'Equipe ciente da reenergização'],
      cuidados: ['Conte a equipe e confirme que ninguém está em contato com o circuito.'],
      erros: ['Religar com pessoas/ferramentas ainda na instalação.'],
      feito: 'Equipe, ferramentas e área conferidas.',
      acao: 'Confirmar conferência',
      acaoTipo: 'confirmar',
      requer: ['des-liberado'],
    },
    {
      id: 'reen-rem-sinalizar',
      titulo: 'Retirar sinalização',
      descricao: 'Remova a sinalização de impedimento.',
      feito: 'Sinalização retirada.',
      acao: 'Retirar sinalização',
      acaoTipo: 'rem-sinalizar',
      requer: ['reen-conferir'],
      focoAnchorId: 'sinalizacao',
    },
    {
      id: 'reen-rem-proteger',
      titulo: 'Retirar proteções',
      descricao: 'Remova barreiras e coberturas isolantes.',
      feito: 'Proteções retiradas.',
      acao: 'Retirar proteções',
      acaoTipo: 'rem-proteger',
      requer: ['reen-rem-sinalizar'],
      focoAnchorId: 'protecao',
    },
    {
      id: 'reen-rem-aterrar',
      titulo: 'Retirar aterramento',
      descricao: 'Remova o aterramento temporário (primeiro dos condutores, depois do terra).',
      detalhes: ['Retirar PRIMEIRO dos condutores', 'Depois do terra/malha'],
      cuidados: ['Ordem inversa do aterramento: condutores primeiro, terra por último.'],
      erros: ['Retirar o terra antes dos condutores.'],
      feito: 'Aterramento temporário retirado.',
      acao: 'Retirar aterramento',
      acaoTipo: 'rem-aterrar',
      requer: ['reen-rem-proteger'],
      focoAnchorId: 'aterramento',
    },
    {
      id: 'reen-rem-bloquear',
      titulo: 'Retirar bloqueio',
      descricao: 'Remova cadeado e etiqueta do dispositivo de manobra.',
      cuidados: ['Só o responsável pelo bloqueio o remove.'],
      feito: 'Bloqueio (LOTO) retirado.',
      acao: 'Retirar bloqueio',
      acaoTipo: 'rem-bloquear',
      requer: ['reen-rem-aterrar'],
      focoAnchorId: 'bloqueio',
    },
    {
      id: 'reen-carregar-mola',
      titulo: 'Carregar a mola do disjuntor',
      descricao: 'Carregue a mola de acionamento antes do fechamento do disjuntor.',
      detalhes: ['Acionar a manivela/motor de carga da mola', 'Aguardar a indicação "mola carregada"'],
      cuidados: ['Confirme a mola totalmente carregada antes de fechar.'],
      erros: ['Tentar fechar com a mola descarregada.'],
      feito: 'Mola carregada — disjuntor pronto para fechar.',
      acao: 'Carregar mola',
      acaoTipo: 'carregar-mola',
      requer: ['reen-rem-bloquear'],
      focoAnchorId: 'disjuntor',
    },
    {
      id: 'reen-religar',
      titulo: 'Religar',
      descricao: 'Feche a seccionadora e o disjuntor, reenergizando o circuito.',
      detalhes: ['Fechar seccionadora', 'Fechar disjuntor', 'Confirmar energização'],
      cuidados: ['Avise a equipe antes de religar. Ninguém em contato com o circuito.'],
      erros: ['Religar sem aviso prévio.', 'Fechar sem a mola carregada.'],
      feito: 'Seccionadora e disjuntor fechados — circuito reenergizado (luz vermelha).',
      acao: 'Fechar disjuntor',
      acaoTipo: 'religar',
      requer: ['reen-carregar-mola'],
      focoAnchorId: 'disjuntor',
    },
    {
      id: 'reen-energizada',
      titulo: 'Subestação reenergizada',
      descricao: 'Circuito reenergizado e em operação. Procedimento concluído.',
      feito: 'Subestação reenergizada e em operação.',
      acao: 'Concluir',
      acaoTipo: 'confirmar',
      requer: ['reen-religar'],
    },
  ],
}
