import type { TestProcedure } from '../types'

/**
 * INSPEÇÃO de subestação — roteiro de verificação (NR-10 / manutenção
 * preventiva). Cada passo é um ponto a inspecionar; o operador marca
 * Conforme / Não conforme. Modo 'inspecao'.
 */
export const inspecaoProcedure: TestProcedure = {
  id: 'inspecao-subestacao',
  nome: 'Inspeção de Subestação',
  norma: 'NR-10 · NBR 14039',
  instrumento: 'checklist',
  engineRef: 'inspecao',
  modo: 'inspecao',
  tensoes: [],
  tensaoPadrao: 0,
  duracaoS: 0,
  steps: [
    {
      id: 'insp-acesso',
      titulo: 'Acesso e sinalização',
      descricao: 'Verifique as condições de acesso e a sinalização de segurança da subestação.',
      detalhes: [
        'Porta/trancas íntegras e identificação do recinto',
        'Placas de advertência "Perigo de Morte / Alta Tensão"',
        'Diagrama unifilar afixado e legível',
        'Disponibilidade de EPI e tapete/estrado isolante',
        'Acesso restrito a pessoal autorizado (NR-10)',
      ],
      acao: 'Avaliar item',
      control: 'insp-check',
      focoAnchorId: 'acesso',
      vista: { pos: [-0.607, 7.922, 2.698], target: [-0.425, 4.878, 1.543] },
      norma: 'NR-10',
    },
    {
      id: 'insp-trafo',
      titulo: 'Transformador',
      descricao: 'Inspecione o estado geral do transformador e seus acessórios.',
      detalhes: [
        'Vazamentos de óleo na cuba, radiadores e juntas',
        'Nível de óleo no visor dentro da faixa',
        'Sílica-gel (azul = ok; rosa = saturada)',
        'Temperatura/termômetro e ruído anormal',
        'Buchas: limpeza, trincas e conexões',
        'Aterramento da carcaça firme',
      ],
      acao: 'Avaliar item',
      requer: ['insp-acesso'],
      control: 'insp-check',
      focoAnchorId: 'trafo',
      vista: { pos: [-0.06, 2.29, 1.372], target: [0.749, 1.748, -0.573] },
    },
    {
      id: 'insp-cubiculos',
      titulo: 'Cubículos e disjuntores',
      descricao: 'Verifique os cubículos de manobra e os dispositivos de proteção.',
      detalhes: [
        'Portas dos cubículos fechadas e travadas',
        'Sinalização de manobra (aberto/fechado/aterrado)',
        'Indicadores e botoeiras operacionais',
        'Intertravamentos funcionando',
        'Ausência de sinais de descarga/carbonização',
      ],
      acao: 'Avaliar item',
      requer: ['insp-trafo'],
      control: 'insp-check',
      focoAnchorId: 'cubiculos',
      vista: { pos: [-2.322, 3.119, 1.76], target: [-1.777, 0.501, -2.702] },
    },
    {
      id: 'insp-aterramento',
      titulo: 'Aterramento',
      descricao: 'Cheque o sistema de aterramento e equipotencialização.',
      detalhes: [
        'Conexões da malha firmes e sem corrosão',
        'Cabos de terra íntegros e identificados (verde-amarelo)',
        'Continuidade das carcaças à malha',
        'Conexões exotérmicas/conectores em bom estado',
      ],
      acao: 'Avaliar item',
      requer: ['insp-cubiculos'],
      control: 'insp-check',
      focoAnchorId: 'aterramento',
      vista: { pos: [-2.164, 1.804, -0.449], target: [-2.775, 1.276, 1.212] },
    },
    {
      id: 'insp-cabos',
      titulo: 'Cabos e conexões',
      descricao: 'Procure por anomalias nos condutores e conexões.',
      detalhes: [
        'Pontos de aquecimento / descoloração (termografia)',
        'Isolação danificada, ressecada ou trincada',
        'Conexões frouxas ou oxidadas',
        'Organização e fixação de cabos/eletrodutos',
        'Raio de curvatura e identificação de fases',
      ],
      acao: 'Avaliar item',
      requer: ['insp-aterramento'],
      control: 'insp-check',
      focoAnchorId: 'cabos',
      vista: { pos: [2.789, 2.027, 0.704], target: [1.948, 1.924, -1.829] },
    },
    {
      id: 'insp-ambiente',
      titulo: 'Iluminação, ventilação e limpeza',
      descricao: 'Avalie as condições ambientais e de combate a incêndio do recinto.',
      detalhes: [
        'Iluminação adequada e iluminação de emergência',
        'Ventilação/exaustão desobstruída',
        'Limpeza geral e ausência de objetos estranhos',
        'Sem infiltração/umidade ou entrada de animais',
        'Extintor adequado, carregado e na validade',
      ],
      acao: 'Avaliar item',
      requer: ['insp-cabos'],
      control: 'insp-check',
      focoAnchorId: 'iluminacao',
      vista: { pos: [-0.923, 4.037, -1.864], target: [0, 3.4, 0] },
    },
    {
      id: 'insp-laudo',
      titulo: 'Emitir laudo',
      descricao: 'Conclua a inspeção e gere o veredito de conformidade da subestação.',
      acao: 'Concluir inspeção',
      requer: ['insp-acesso', 'insp-trafo', 'insp-cubiculos', 'insp-aterramento', 'insp-cabos', 'insp-ambiente'],
      vista: { pos: [0.11, 9.663, 0.832], target: [0, 1, -0.5] },
    },
  ],
}
